# Generated by Django 5.1.7 on 2025-04-30 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='lots',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='status_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage (e.g., 2 for 2%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='lot_number',
            field=models.CharField(blank=True, default='Lot-', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='InventoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity affected by this status change', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the status change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_status_changes', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_statuses', to='Accounts.purchaseinvoice')),
            ],
            options={
                'verbose_name': 'Inventory Status',
                'verbose_name_plural': 'Inventory Statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
