# Generated by Django 5.1.7 on 2025-04-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_salesinvoice_lots_purchaseinvoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
